name: Sample Service Pipeline

on:
  push:
    branches:
      [ 'master' ]

jobs:
  Build:
    environment:
      name: Build
    runs-on:
      [ ubuntu-latest ]
    strategy:
      matrix:
        python-version:
          [ "3.8" ]
    steps:
      - name: 'Checkout Repository.'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version:
            ${{ matrix.python-version }}
      - name: 'Set up Flask'
        run: |
          export FLASK_DEBUG=1
      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [[ "${FLASK_DEBUG}" == "1" ]]; then python -m pip install -r requirements/dev.txt; else python -m pip install -r requirements.txt; fi
      - name: 'Run pytest'
        run: |
          pytest tests/

  Alpha:
    name: Deploy to Alpha Stage
    needs:
      [ Build ]
    runs-on:
      [ ubuntu-latest ]
    environment:
      name: Alpha
    steps:
      - name: blah
        run: echo 'blah'

  Beta:
    name: Deploy to Beta Stage
    needs:
      [ Alpha ]
    runs-on:
      [ ubuntu-latest ]
    environment:
      name: Beta
    steps:
      - name: blah
        run: echo 'blah'

  Gamma:
    name: Deploy to Gamma Stage
    needs:
      [ Beta ]
    runs-on:
      [ ubuntu-latest ]
    environment:
      name: Gamma
    steps:
      - name: blah
        run: echo 'blah'

  Prod:
    name: Deploy to Prod Stage
    needs:
      [ Gamma ]
    runs-on:
      [ ubuntu-latest ]
    environment:
      name: Prod
    steps:
      - name: blah
        run: echo 'blah'
